# Generated by Django 4.1 on 2022-08-31 10:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbudata',
            name='reach',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
