# Generated by Django 4.1 on 2022-08-31 13:13

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbu', '0002_alter_cbudata_reach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbudata',
            name='reach',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usertable', to=settings.AUTH_USER_MODEL),
        ),
    ]
